name: 'Package plugin'
description: 'Packages the plugin for specified architecture and build config.'
inputs:
  target:
    description: 'Build target for dependencies'
    required: true
  config:
    description: 'Build configuration'
    required: false
    default: 'RelWithDebInfo'
  package:
    description: 'Create Windows installation package'
    required: false
    default: 'false'
  workingDirectory:
    description: 'Working directory for packaging'
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - name: Install Dependencies ðŸ›ï¸
      if: runner.os == 'Linux'
      shell: bash
      run: |
        : Install Dependencies ðŸ›ï¸
        echo ::group::Install Dependencies
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
        brew install --quiet zsh
        echo ::endgroup::

    - name: Run Windows Packaging
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # Run Windows Packaging
        if ( $Env:RUNNER_DEBUG -ne $null ) {
          Set-PSDebug -Trace 1
        }

        $PackageArgs = @{
          Target = '${{ inputs.target }}'
          Configuration = '${{ inputs.config }}'
        }

        if ( '${{ inputs.package }}' -eq 'true' ) {
          $PackageArgs += @{BuildInstaller = $true}
        }

        .github/scripts/Package-Windows.ps1 @PackageArgs
